version: '0.1'
name: 'my_simple_dbt_project'


profile: 'my_dbt_project'

model-paths: ["models"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


vars:
    my_name: "No entry"

models:
    my_dbt_project:
        staging:
          +materialized: view
          schema: staging
        marts:
          +materialized: table
          schema: marts
